### ISSUE TITLE
[Feature] 아이템 시스템 설계

### ISSUE THREAD

**Issue by password-kim** [KIA-PROGRAMMING-38/Moonlighter#14]
# 설명
게임에서 사용될 아이템 시스템을 설계합니다.

# 아이템 카테고리
- 장비
    - 무기
        - 검,방패
        - 대검
        - 창
        - 장갑
        - 활
    - 갑옷
        - 머리 방어구
        - 가슴 방어구
        - 신발 방어구
- 소모성 아이템
    - HP 포션
- 재료 아이템
    - 장비 or 소모성 아이템 제작을 위한 재료.

**Comment by ChoiSeonMun** [comment]
아이템 시스템부터 역기획하고 진행해야 갈피를 잡을 수 있을 것으로 보임.
